name: test1

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test job name"
    steps:
    - name: step1
      run: |
        echo "start sleeping"
        sleep 200
        echo "Done sleeping"
